### ISSUE TITLE
Onde baixo esse "present"?

### ISSUE THREAD

**Issue by bernardolm** [wpjunior/etcd-slides#1]

**Comment by wpjunior** [comment]
Olá @bernardolm, tá na mão: https://godoc.org/golang.org/x/tools/present

Abraços

**Comment by bernardolm** [comment]
Muito obrigado, @wpjunior!

**Comment by bernardolm** [comment]
Para futuras consultas, instalar **present** usando `go install golang.org/x/tools/cmd/present` para conseguir rodar a apresentação ;)
